# Generated by Django 5.1 on 2025-11-20 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_payment_terms'),
        ('consulting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_contact', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='consulting.consultingproject')),
            ],
        ),
        migrations.CreateModel(
            name='ClientHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.PositiveIntegerField(default=100)),
                ('satisfaction_score', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('engagement_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=20)),
                ('last_contact_date', models.DateField(auto_now=True)),
                ('risk_factors', models.TextField(blank=True, help_text='JSON list of risk factors')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to=settings.AUTH_USER_MODEL)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('skills', models.TextField(help_text='Comma-separated list of skills')),
                ('target_utilization', models.PositiveIntegerField(default=80)),
                ('current_utilization', models.PositiveIntegerField(default=0)),
                ('billable_hours_ytd', models.PositiveIntegerField(default=0)),
                ('revenue_ytd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('availability_status', models.CharField(default='Available', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='consulting.consultingproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('probability', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('mitigation_plan', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MITIGATED', 'Mitigated'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='consulting.consultingproject')),
            ],
        ),
    ]
