# Generated by Django 5.1 on 2025-11-07 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iso_standards',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('INITIAL', 'Initial Certification'), ('SURVEILLANCE', 'Surveillance Audit'), ('RECERTIFICATION', 'Recertification'), ('SPECIAL', 'Special Audit')], max_length=20)),
                ('audit_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scope', models.TextField()),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='PLANNED', max_length=20)),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('major_findings', models.PositiveIntegerField(default=0)),
                ('minor_findings', models.PositiveIntegerField(default=0)),
                ('opportunities', models.PositiveIntegerField(default=0)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_issue_date', models.DateField(blank=True, null=True)),
                ('certificate_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditors', models.ManyToManyField(blank=True, related_name='audits_assigned', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_created', to=settings.AUTH_USER_MODEL)),
                ('lead_auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_lead', to=settings.AUTH_USER_MODEL)),
                ('iso_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.isostandard')),
            ],
            options={
                'db_table': 'audits',
                'ordering': ['-planned_start_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('iso_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.isostandard')),
            ],
            options={
                'db_table': 'audit_checklists',
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_number', models.CharField(max_length=50)),
                ('finding_type', models.CharField(choices=[('MAJOR', 'Major Non-Conformity'), ('MINOR', 'Minor Non-Conformity'), ('OPPORTUNITY', 'Opportunity for Improvement'), ('OBSERVATION', 'Observation')], max_length=20)),
                ('clause_reference', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('evidence', models.TextField()),
                ('requirement', models.TextField()),
                ('correction', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('actual_closure_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed'), ('VERIFIED', 'Verified')], default='OPEN', max_length=20)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.audit')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_findings',
                'ordering': ['finding_number'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_reference', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('REQUIREMENT', 'Requirement'), ('PROCESS', 'Process'), ('DOCUMENT', 'Document'), ('RECORD', 'Record')], max_length=20)),
                ('question', models.TextField()),
                ('guidance', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audits.auditchecklist')),
            ],
            options={
                'db_table': 'checklist_items',
                'ordering': ['order'],
            },
        ),
    ]
