# Generated by Django 5.1 on 2025-11-13 19:46

import apps.audits.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchecklist',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='enable_actions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='enable_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='enable_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='footer_content',
            field=models.TextField(blank=True, help_text='Footer content for template'),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='header_content',
            field=models.TextField(blank=True, help_text='Header content for template'),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='include_compliance_checkboxes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image for template header', null=True, upload_to=apps.audits.models.template_logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='primary_color',
            field=models.CharField(default='#2563eb', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='actions_required',
            field=models.TextField(blank=True, help_text='Actions required for this item'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='allow_evidence_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='allow_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='iso_clause',
            field=models.CharField(blank=True, help_text='ISO standard clause reference', max_length=50),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='section_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='subsection',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='item_type',
            field=models.CharField(choices=[('REQUIREMENT', 'Requirement'), ('PROCESS', 'Process'), ('DOCUMENT', 'Document'), ('RECORD', 'Record'), ('OBSERVATION', 'Observation'), ('CONTROL', 'Control')], max_length=20),
        ),
        migrations.CreateModel(
            name='AuditChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_status', models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('needs_improvement', 'Needs Improvement'), ('non_compliant', 'Non-Compliant'), ('not_applicable', 'Not Applicable'), ('pending', 'Pending Review')], max_length=20, null=True)),
                ('auditor_comments', models.TextField(blank=True)),
                ('auditor_notes', models.TextField(blank=True)),
                ('actions_taken', models.TextField(blank=True)),
                ('evidence_description', models.TextField(blank=True)),
                ('corrective_action_required', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='audits.audit')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.checklistitem')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_checklist_responses',
                'unique_together': {('audit', 'checklist_item')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Supported formats: PDF, DOC, DOCX, JPG, JPEG, PNG, XLSX, XLS', upload_to=apps.audits.models.evidence_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xlsx', 'xls'])])),
                ('filename', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='audits.auditchecklistresponse')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checklist_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='audits.auditchecklist')),
            ],
            options={
                'db_table': 'checklist_sections',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='audits.checklistsection'),
        ),
    ]
