# Generated by Django 5.1 on 2025-11-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auditchecklist_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='audit_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='audits.auditchecklist'),
        ),
    ]
