# Generated by Django 5.1 on 2025-11-13 21:46

import apps.audits.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_audit_audit_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Supported formats: PDF, DOC, DOCX, JPG, JPEG, PNG, XLSX, XLS, TXT', upload_to=apps.audits.models.audit_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xlsx', 'xls', 'txt'])])),
                ('filename', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('EVIDENCE', 'Evidence'), ('REPORT', 'Report'), ('CERTIFICATE', 'Certificate'), ('CORRESPONDENCE', 'Correspondence'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audits.audit')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audit_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
