# Generated by Django 5.1 on 2025-11-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_auditdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='isostandard',
            name='default_template',
            field=models.ForeignKey(blank=True, help_text='Default audit template for this standard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_standards', to='audits.auditchecklist'),
        ),
    ]
