# Generated by Django 5.1 on 2025-11-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_isostandard_default_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_type',
            field=models.CharField(choices=[('INITIAL', 'Initial Certification'), ('SURVEILLANCE_1', '1st Surveillance'), ('SURVEILLANCE_2', '2nd Surveillance'), ('RECERTIFICATION', 'Recertification'), ('SPECIAL', 'Special Audit')], max_length=20),
        ),
    ]
