# Generated by Django 5.1 on 2025-11-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_alter_audit_audit_type'),
        ('job_pipeline', '0002_jobpipeline_number_alter_jobpipeline_pipeline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='job_pipeline.jobpipeline'),
        ),
    ]
