# Generated by Django 5.1 on 2025-11-13 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_address_line_1_and_more'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('DYNAMIC', 'Dynamic')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('MPESA', 'M-Pesa'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='employees.employee')),
            ],
            options={
                'db_table': 'payroll',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('TAX', 'Tax'), ('INSURANCE', 'Insurance'), ('PENSION', 'Pension/Retirement'), ('LOAN', 'Loan Repayment'), ('ADVANCE', 'Salary Advance'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='finance.payroll')),
            ],
            options={
                'db_table': 'payroll_deductions',
                'ordering': ['deduction_type'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_type', models.CharField(choices=[('BONUS', 'Bonus'), ('COMMISSION', 'Commission'), ('OVERTIME', 'Overtime'), ('ALLOWANCE', 'Allowance'), ('REIMBURSEMENT', 'Reimbursement'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='finance.payroll')),
            ],
            options={
                'db_table': 'payroll_earnings',
                'ordering': ['earning_type'],
            },
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'start_date'], name='payroll_employe_f864a8_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payroll_status_ac0f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['payment_date'], name='payroll_payment_3125a4_idx'),
        ),
    ]
