# Generated by Django 5.1 on 2025-11-20 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_development', '0003_contract_additional_fees_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.CharField(help_text='Unique pipeline identifier', max_length=50, unique=True)),
                ('client_name', models.CharField(help_text='Client organization name', max_length=255)),
                ('service_description', models.TextField(help_text='Description of services')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('current_stage', models.CharField(choices=[('LEAD', 'Lead'), ('OPPORTUNITY', 'Opportunity'), ('CONTRACT', 'Contract'), ('AUDIT_SCHEDULED', 'Audit Scheduled'), ('AUDIT_IN_PROGRESS', 'Audit In Progress'), ('AUDIT_COMPLETED', 'Audit Completed'), ('CERTIFICATE_ISSUED', 'Certificate Issued'), ('SURVEILLANCE_DUE', 'Surveillance Due'), ('CLOSED', 'Closed')], default='LEAD', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('lead_created_date', models.DateTimeField(blank=True, null=True)),
                ('opportunity_created_date', models.DateTimeField(blank=True, null=True)),
                ('contract_signed_date', models.DateTimeField(blank=True, null=True)),
                ('audit_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('audit_completed_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_issued_date', models.DateTimeField(blank=True, null=True)),
                ('next_milestone', models.CharField(blank=True, max_length=255)),
                ('next_milestone_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='business_development.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pipelines', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='business_development.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='business_development.opportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_pipelines',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('PROPOSAL_DUE', 'Proposal Due'), ('CONTRACT_SIGNATURE', 'Contract Signature'), ('AUDIT_SCHEDULED', 'Audit Scheduled'), ('AUDIT_START', 'Audit Start'), ('AUDIT_COMPLETION', 'Audit Completion'), ('CERTIFICATE_ISSUE', 'Certificate Issue'), ('SURVEILLANCE_DUE', 'Surveillance Due'), ('RECERTIFICATION_DUE', 'Recertification Due'), ('CONTRACT_RENEWAL', 'Contract Renewal'), ('CUSTOM', 'Custom Milestone')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='job_pipeline.jobpipeline')),
            ],
            options={
                'db_table': 'pipeline_milestones',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('LEAD', 'Lead'), ('OPPORTUNITY', 'Opportunity'), ('CONTRACT', 'Contract'), ('AUDIT_SCHEDULED', 'Audit Scheduled'), ('AUDIT_IN_PROGRESS', 'Audit In Progress'), ('AUDIT_COMPLETED', 'Audit Completed'), ('CERTIFICATE_ISSUED', 'Certificate Issued'), ('SURVEILLANCE_DUE', 'Surveillance Due'), ('CLOSED', 'Closed')], max_length=20)),
                ('to_stage', models.CharField(choices=[('LEAD', 'Lead'), ('OPPORTUNITY', 'Opportunity'), ('CONTRACT', 'Contract'), ('AUDIT_SCHEDULED', 'Audit Scheduled'), ('AUDIT_IN_PROGRESS', 'Audit In Progress'), ('AUDIT_COMPLETED', 'Audit Completed'), ('CERTIFICATE_ISSUED', 'Certificate Issued'), ('SURVEILLANCE_DUE', 'Surveillance Due'), ('CLOSED', 'Closed')], max_length=20)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='job_pipeline.jobpipeline')),
                ('transitioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pipeline_stage_transitions',
                'ordering': ['-transitioned_at'],
            },
        ),
    ]
