# Generated by Django 5.1 on 2025-11-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpipeline',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential pipeline number', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpipeline',
            name='pipeline_id',
            field=models.CharField(blank=True, help_text='Unique pipeline identifier', max_length=50, unique=True),
        ),
    ]
