# Generated by Django 5.1 on 2025-11-12 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='annual_revenue',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_since',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='county',
        ),
        migrations.RemoveField(
            model_name='client',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_contact_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_contact_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_contact_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_contact_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(default='', help_text='Primary address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certification standards'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(default='', help_text='Primary contact person name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', help_text='Primary contact email', max_length=254, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='health_score',
            field=models.IntegerField(default=100, help_text='Client health score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='client',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', help_text='Client/Company name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='next_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', help_text='Primary contact phone', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='site_contact',
            field=models.CharField(blank=True, help_text='Site contact person', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='site_phone',
            field=models.CharField(blank=True, help_text='Site phone number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('at-risk', 'At Risk'), ('churned', 'Churned')], default='active', max_length=20),
        ),
    ]
