# Generated by Django 5.1 on 2025-11-12 16:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intakelink',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='intakesubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='intakelink',
            name='access_code',
            field=models.CharField(default='TEMP-0000', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intakelink',
            name='current_uses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intakelink',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakelink',
            name='max_uses',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='intakelink',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='intakelink',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intakelink',
            name='related_audit_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intakelink',
            name='related_project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_submissions', to='clients.client'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='intakelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 12, 16, 10, 21, 840996, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intakelink',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='intakelink',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='intakelink',
            index=models.Index(fields=['token'], name='intake_link_token_c3d80c_idx'),
        ),
        migrations.AddIndex(
            model_name='intakelink',
            index=models.Index(fields=['is_active', 'expires_at'], name='intake_link_is_acti_f3b485_idx'),
        ),
        migrations.AddIndex(
            model_name='intakesubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='intake_subm_status_9db2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='intakesubmission',
            index=models.Index(fields=['intake_link', 'submitted_at'], name='intake_subm_intake__86f702_idx'),
        ),
    ]
