# Generated by Django 5.1 on 2025-11-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_spreadsheet_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Payment terms', max_length=255, null=True),
        ),
    ]
