# Generated by Django 5.1 on 2025-11-12 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='audit_count',
            field=models.PositiveIntegerField(default=0, help_text='Total audits completed'),
        ),
        migrations.AddField(
            model_name='employee',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications'),
        ),
        migrations.AddField(
            model_name='employee',
            name='commission_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission rate per audit', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='department_name',
            field=models.CharField(blank=True, help_text='Department name for display', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Languages spoken'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, help_text='Job role/title (e.g., lead-auditor, auditor, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='satisfaction',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Satisfaction rating 0-5', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='utilization',
            field=models.PositiveIntegerField(default=0, help_text='Utilization percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
