# Generated by Django 5.1 on 2025-11-14 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_payment_terms'),
        ('employees', '0003_alter_employee_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Billable amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='billable_status',
            field=models.CharField(choices=[('BILLABLE', 'Billable'), ('NON_BILLABLE', 'Non-Billable'), ('INTERNAL', 'Internal')], default='BILLABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='billed_status',
            field=models.CharField(choices=[('UNBILLED', 'Unbilled'), ('BILLED', 'Billed'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid')], default='UNBILLED', max_length=20),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='certificate_no',
            field=models.CharField(blank=True, help_text='Certificate or project number', max_length=100),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='clients.client'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='notes',
            field=models.TextField(blank=True, help_text='Location or additional notes'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='task_name',
            field=models.CharField(choices=[('1ST_SURVEILLANCE', '1st Surveillance Audit'), ('2ND_SURVEILLANCE', '2nd Surveillance Audit'), ('RE_CERTIFICATION', 'Re-certification Audit'), ('INITIAL_CERTIFICATION', 'Initial Certification Audit'), ('GAP_ANALYSIS', 'Gap Analysis'), ('CONSULTING', 'Consulting'), ('TRAINING', 'Training'), ('ADMIN', 'Administrative')], default='ADMIN', max_length=30),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='project_code',
            field=models.CharField(blank=True, help_text='Project or client code', max_length=50),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['employee', 'date'], name='timesheets_employe_0b9a40_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['billable_status'], name='timesheets_billabl_8dcee3_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['billed_status'], name='timesheets_billed__aadab2_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['certificate_no'], name='timesheets_certifi_30a40a_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['client'], name='timesheets_client__0100bb_idx'),
        ),
    ]
