# Generated by Django 5.1 on 2025-11-13 10:17

import apps.certifications.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('clients', '0003_alter_intakelink_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('template_type', models.CharField(choices=[('jasper', 'JasperReports (.jrxml)'), ('docx', 'Microsoft Word (.docx)'), ('pdf', 'PDF Template'), ('html', 'HTML Template')], default='docx', max_length=20)),
                ('template_file', models.FileField(help_text='Template file', upload_to=apps.certifications.models.certificate_template_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jrxml', 'docx', 'pdf', 'html'])])),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Template variable definitions and default values')),
                ('is_active', models.BooleanField(default=True, help_text='Is this template active?')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default template for its ISO standard?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to=settings.AUTH_USER_MODEL)),
                ('iso_standard', models.ForeignKey(blank=True, help_text='ISO standard this template is for (null for generic templates)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='audits.isostandard')),
            ],
            options={
                'db_table': 'certificate_templates',
                'ordering': ['-created_at'],
                'unique_together': {('iso_standard', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(help_text='Unique certificate number', max_length=100, unique=True)),
                ('issue_date', models.DateField(help_text='Date certificate was issued')),
                ('expiry_date', models.DateField(help_text='Date certificate expires')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expiring-soon', 'Expiring Soon'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('scope', models.TextField(help_text='Certification scope')),
                ('certification_body', models.CharField(blank=True, help_text='Name of certification body', max_length=255)),
                ('accreditation_number', models.CharField(blank=True, help_text='Accreditation number', max_length=100)),
                ('document_url', models.FileField(blank=True, help_text='Generated certificate document', null=True, upload_to=apps.certifications.models.generated_certificate_path)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional certification metadata')),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(blank=True, help_text='The audit that resulted in this certification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='audits.audit')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certifications', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_created', to=settings.AUTH_USER_MODEL)),
                ('iso_standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audits.isostandard')),
                ('lead_auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_audited', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='certifications.certificatetemplate')),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('issued', 'Issued'), ('renewed', 'Renewed'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('reactivated', 'Reactivated'), ('updated', 'Updated'), ('document_generated', 'Document Generated')], max_length=30)),
                ('previous_status', models.CharField(blank=True, help_text='Status before action', max_length=20)),
                ('new_status', models.CharField(blank=True, help_text='Status after action', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes about this action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional action metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='certifications.certification')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Certification histories',
                'db_table': 'certification_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['status', 'expiry_date'], name='certificati_status_0830c8_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['client', 'status'], name='certificati_client__d45bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['certificate_number'], name='certificati_certifi_cd449c_idx'),
        ),
    ]
