# Generated by Django 5.1 on 2025-11-20 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_development', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='signed_by_client',
            new_name='signed_by_client_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='client',
        ),
        migrations.AddField(
            model_name='contract',
            name='agreement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cancellation_fee_applies',
            field=models.BooleanField(default=True, help_text='Whether full audit fee applies for late cancellations'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cancellation_notice_days',
            field=models.PositiveIntegerField(default=15, help_text='Working days notice required for cancellation/rescheduling'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cb_address',
            field=models.TextField(default='168 City Road, Cardiff, Wales, CF24 3JE, United Kingdom'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cb_name',
            field=models.CharField(default='AceQu International Limited', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='cb_role',
            field=models.TextField(default='Accredited Certification Body providing ISO certification audits'),
        ),
        migrations.AddField(
            model_name='contract',
            name='certificate_issue_days',
            field=models.PositiveIntegerField(default=14, help_text='Working days to issue certificate after NC closure'),
        ),
        migrations.AddField(
            model_name='contract',
            name='certification_cycle_years',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_contact_person',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_email',
            field=models.EmailField(default='contact@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_organization',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_responsibilities',
            field=models.JSONField(default=list, help_text='List of client responsibilities and commitments'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_secondary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='confidentiality_clause',
            field=models.TextField(default='AceQu will keep all client information confidential except when required by law or accreditation rules.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='data_protection_compliance',
            field=models.TextField(default='AceQu must store and process data securely following GDPR and other applicable regulations.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='fee_per_standard_year_1',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Certification audit fee per standard (Year 1)', max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='fee_per_standard_year_2',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Surveillance audit fee per standard (Year 2)', max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='fee_per_standard_year_3',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Surveillance audit fee per standard (Year 3)', max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='iso_standards',
            field=models.JSONField(default=list, help_text="List of ISO standards, e.g., ['ISO 9001:2015', 'ISO 14001:2015', 'ISO 45001:2018']"),
        ),
        migrations.AddField(
            model_name='contract',
            name='nc_closure_max_days',
            field=models.PositiveIntegerField(default=60, help_text='Maximum days to close non-conformities'),
        ),
        migrations.AddField(
            model_name='contract',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='business_development.opportunity'),
        ),
        migrations.AddField(
            model_name='contract',
            name='recertification_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recertification audit fee (if determined)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='recertification_fee_tbd',
            field=models.BooleanField(default=True, help_text='Whether recertification fee is to be determined'),
        ),
        migrations.AddField(
            model_name='contract',
            name='scope_of_work',
            field=models.TextField(default='', help_text='Detailed scope of certification work'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_client_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_company_name',
            field=models.CharField(default='Kuldip Degon, PCQI', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_company_position',
            field=models.CharField(default='Lead Auditor, AceQu International Ltd', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='site_covered',
            field=models.TextField(default='', help_text='Physical location/site covered by this contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stage_1_audit_days',
            field=models.PositiveIntegerField(default=1, help_text='Stage I audit duration in days'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stage_1_remote_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='stage_1_stage_2_max_gap_days',
            field=models.PositiveIntegerField(default=90, help_text='Maximum days between Stage I and Stage II audits'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stage_2_audit_days',
            field=models.PositiveIntegerField(default=3, help_text='Stage II audit duration in days'),
        ),
        migrations.AddField(
            model_name='contract',
            name='surveillance_audit_frequency',
            field=models.CharField(default='Annual', help_text='Frequency of surveillance audits (e.g., Annual, Semi-annual)', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_notice_days',
            field=models.PositiveIntegerField(default=30, help_text='Days notice required for termination'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='contract',
            name='duration_months',
            field=models.PositiveIntegerField(default=36, help_text='Contract duration in months'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_schedule',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_by_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_signed', to=settings.AUTH_USER_MODEL),
        ),
    ]
