# Generated by Django 5.1 on 2025-11-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_development', '0002_rename_signed_by_client_contract_signed_by_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='additional_fees_description',
            field=models.TextField(blank=True, default='Follow-up audits (closing NCs), Scope extensions, Major operational changes', help_text='Description of additional fees that may apply'),
        ),
        migrations.AddField(
            model_name='contract',
            name='certificate_validity_extension_allowed',
            field=models.BooleanField(default=False, help_text='Validity cannot be extended except through recertification'),
        ),
        migrations.AddField(
            model_name='contract',
            name='certificate_validity_years',
            field=models.PositiveIntegerField(default=3, help_text='Certificate validity in years, with mandatory annual surveillance audits'),
        ),
        migrations.AddField(
            model_name='contract',
            name='entire_agreement_clause',
            field=models.TextField(default='This is the entire agreement. Amendments must be in writing and signed by both parties.', help_text='Entire agreement clause text'),
        ),
        migrations.AddField(
            model_name='contract',
            name='recertification_audit_description',
            field=models.TextField(default='Man-days similar to Stage II unless changes occur.', help_text='Description of recertification audit process'),
        ),
        migrations.AddField(
            model_name='contract',
            name='recertification_audit_timing',
            field=models.CharField(default='3 months before certificate expiry', help_text='When recertification audit is conducted', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='stage_1_audit_description',
            field=models.TextField(default='Reviews documentation, readiness, and preparedness.', help_text='Description of Stage I audit process'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stage_2_audit_description',
            field=models.TextField(default='Full assessment of implementation and conformity to standards. Subject to change based on growth.', help_text='Description of Stage II audit process'),
        ),
        migrations.AddField(
            model_name='contract',
            name='surveillance_audit_description',
            field=models.TextField(default='Year 2 and Year 3 - Annual audits to verify ongoing conformity.', help_text='Description of surveillance audit process'),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_fee_waiver',
            field=models.BooleanField(default=False, help_text='Termination does not waive fees for completed or confirmed audits'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='certificate_issue_days',
            field=models.PositiveIntegerField(default=14, help_text='Certificates issued within this many working days after NC closure'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='nc_closure_max_days',
            field=models.PositiveIntegerField(default=60, help_text='Non-conformities must be closed within this many days max'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='stage_1_remote_allowed',
            field=models.BooleanField(default=True, help_text='Can be on-site or remote'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='stage_1_stage_2_max_gap_days',
            field=models.PositiveIntegerField(default=90, help_text='Stage I & Stage II must be completed within this many days of each other'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='termination_notice_days',
            field=models.PositiveIntegerField(default=30, help_text='Either party may terminate with this many days written notice'),
        ),
    ]
