# Generated by Django 5.1 on 2025-11-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_development', '0003_contract_additional_fees_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
