# Generated by Django 5.1 on 2025-11-28 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_development', '0004_alter_contract_contract_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='template_version_used',
            field=models.CharField(blank=True, help_text='Version of template used', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(help_text='ID from template builder', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('CERTIFICATION_CONTRACT', 'Certification Contract'), ('SERVICE_AGREEMENT', 'Service Agreement'), ('CONSULTING_AGREEMENT', 'Consulting Agreement'), ('NDA', 'Non-Disclosure Agreement'), ('SOW', 'Statement of Work')], max_length=30)),
                ('template_data', models.JSONField(help_text='Complete template data from template builder including pages, sections, and metadata')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default template for this type?')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates_created', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='business_development.contracttemplate')),
            ],
            options={
                'db_table': 'contract_templates',
                'ordering': ['-created_at'],
                'unique_together': {('template_type', 'version', 'is_default')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_template',
            field=models.ForeignKey(blank=True, help_text='Template used to generate this contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contracts', to='business_development.contracttemplate'),
        ),
    ]
